### ISSUE TITLE
10.10 compatible ?

### ISSUE THREAD

**Issue by johnno1962** [erwanb/MachInjectSample#4]
Hi, I’ve just tried running this project under 10.10 and I get the following error:

2016-06-15 17:08:24.041 MachInjectSample[2454:31915] Injecting Finder (317) with /Users/johnholdsworth/Library/Developer/Xcode/DerivedData/MachInjectSample-geshmsepcxcvcedqvwrajxmdtfja/Build/Products/Debug/MachInjectSample.app/Contents/Resources/Payload.bundle
2016-06-15 17:08:24.063 MachInjectSample[2454:31915] an error occurred while injecting Finder: (os/kern) failure (error code: 5)
2016-06-15 17:08:24.063 MachInjectSample[2454:31915] Couldn't inject Finder (domain: com.erwanb.MachInjectSample.ErrorDomain code: 3)

Console logs:
15/06/2016 17:08:24.042 MachInjectSample[2454]: Injecting Finder (317) with /Users/johnholdsworth/Library/Developer/Xcode/DerivedData/MachInjectSample-geshmsepcxcvcedqvwrajxmdtfja/Build/Products/Debug/MachInjectSample.app/Contents/Resources/Payload.bundle
15/06/2016 17:08:24.063 MachInjectSample[2454]: an error occurred while injecting Finder: (os/kern) failure (error code: 5)
15/06/2016 17:08:24.063 MachInjectSample[2454]: Couldn't inject Finder (domain: com.erwanb.MachInjectSample.ErrorDomain code: 3)
15/06/2016 17:08:24.128 sandboxd[150]: ([2457]) com.erwanb.MachI(2457) System Policy: deny mach-priv-task-port

Is this expected with SIP and the like? Everything was signed with a valid Apple dev id.

I cloned your project and then copied in mach_inject/{mach_inject,mach_inject_bundle,mach_inject_bundle_stub} from https://github.com/rentzsch/mach_inject, then tried: git clone https://github.com/erwanb/MachInjectSample --recurse-submodules

**Comment by erwanb** [comment]
This project has been fixed to work under 10.10, see [this issue](https://github.com/rentzsch/mach_inject/issues/13).
You can find it [here](https://github.com/rentzsch/mach_inject/tree/semver-1.x/mach_inject_example).

**Comment by johnno1962** [comment]
Thanks for the prompt reply. Will the project work under 10.11 do you know? I’ve not had any luck

**Comment by erwanb** [comment]
I don't follow the subject closely, but it seems Apple with SIP is determined to crack down on code injection.
Check this [issue](https://github.com/rentzsch/mach_inject/issues/17) for a possible solution.

**Comment by johnno1962** [comment]
Yes, it seems the only answer is to turn SIP off. Thanks again.
